options:
  routerhost:
    default: localhost
    description: The name of the SPARKL router for websocket based comms
    type: string
  hostport:
    default: 8000
    description: The port of the SPARKL router for websocket based comms
    type: int
  origreplyto:
    default: none
    description: Base 64 encoding of erlang process responsible for provisioning service
    type: string
  serviceport:
    default: 8888
    description: Port used to contact the service on
    type: int
